In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

In [ ]:
df=pd.read_csv("Churn_Modelling.csv")

In [ ]:
df.head(4)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0

[4 rows x 14 columns]

In [ ]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer


In [34]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [35]:
print(x)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

AttributeError: ignored

feature scaling.....is must for every deep learning

In [39]:
 from sklearn.preprocessing import StandardScaler
 sc=StandardScaler()
 x_train=sc.fit_transform(x_train)
 x_test=sc.transform(x_test) 

**bold text**

In [40]:
ann=tf.keras.models.Sequential()

In [41]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

2nd layer

In [42]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

output layer

In [43]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

**training ANN**

In [44]:
#compile
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

**training on trainset**

In [45]:
ann.fit(x_train,y_train,batch_size=32,epochs=90)

Epoch 1/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4914 - accuracy: 0.7964
Epoch 2/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.8058
Epoch 3/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4305 - accuracy: 0.8110
Epoch 4/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4226 - accuracy: 0.8170
Epoch 5/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4162 - accuracy: 0.8202
Epoch 6/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4103 - accuracy: 0.8236
Epoch 7/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4051 - accuracy: 0.8246
Epoch 8/90
250/250 [==============================] - 0s 1ms/step - loss: 0.4006 - accuracy: 0.8263
Epoch 9/90
250/250 [==============================] - 0s 1ms/step - loss: 0.3955 - accuracy: 0.8274
Epoch 10/90
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8279

In [49]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


**predictions** on test set

In [51]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate( (y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1498   97]
 [ 175  230]]


0.864